### ISSUE TITLE
Thanx for Diff.Net

### ISSUE THREAD

**Issue by Dirkster99** [menees/Diff.Net#1]
Hey Bill,

I like Diff.Net and even build a WPF clone [Ähnlich](https://github.com/Dirkster99/Aehnlich) based on your excellent [back-end library](https://github.com/Dirkster99/Aehnlich/tree/master/source/AehnlichLib). Your software design is supporior and the application is more than useful compared to other open-source attempts available on the Internet. Just want to say thank you for sharing such a great piece of work 🥇 

Thanx Dirk

**Comment by menees** [comment]
Awesome! You're welcome, and thanks for the kind words. Your WPF clone is cool, and it's really nice to see this code helping other people out.
