### ISSUE TITLE
can this also be put on NuGet?

### ISSUE THREAD

**Issue by bkwdesign** [menees/Diff.Net#2]
Awesome work. And..   Thank You.

I have my own WinForms application that does some interactions with a government RestFul API
In the course of things, I allow the more technical user the ability to see the JSON passed back-n-forth and actually "diff" the JSON if an interaction has been logged multiple times (so user can readily see what changed since they last submitted the object graph)

I currently embed your **older** Diff.Net.exe inside my application and then call it like this:
```csharp
Process.Start("Diff.Net.exe", $"\"{file1.FullName}\" \"{file2.FullName}\" /f:w+c+g-tt");
```
If I want to use the more modern nuget-ized versions of your DLLs.. I believe I should link out to this package `Menees.Diffs.Windows.Forms` and thus I get all these:

```xml
  <package id="Menees.Common" version="4.9.10" targetFramework="net462" />
  <package id="Menees.Diffs" version="4.9.10" targetFramework="net462" />
  <package id="Menees.Diffs.Windows.Forms" version="4.9.10" targetFramework="net462" />
  <package id="Menees.Windows" version="4.9.10" targetFramework="net462" />
  <package id="Menees.Windows.Forms" version="4.9.10" targetFramework="net462" />
```
I don't know how to get the actual exe into my application via NuGet or if I should be instantiating one of your form instances..  
So, my question is: 
Can you either nuget-ize this Diff.Net application, or put some more help docs out there so I can more readily discern what the equivalent C# code would be

**Comment by menees** [comment]
You just need a PackageReference to [Menees.Diffs.Windows.Forms](https://www.nuget.org/packages/Menees.Diffs.Windows.Forms/), and then it should implicitly pull in all the dependent references (i.e., the other four Menees libraries). Then you can create a DiffControl instance and show it in your application. I discuss this a little in my [Libraries repo issue #1](https://github.com/menees/Libraries/issues/1).
