### ISSUE TITLE
Allow edit on the textbox and can get either left or right box value

### ISSUE THREAD

**Issue by kykm1307** [menees/Diff.Net#3]
how do I allow edit on the diffcontrol box and can get either left or right box value in the code?

**Comment by menees** [comment]
The controls in [Menees.Diffs.Windows.Forms](https://github.com/menees/Libraries/tree/master/src/Menees.Diffs.Windows.Forms) don't support editing. They're all read-only (i.e., view-only) controls, so the value in a control will never change from what you initialize it with.
