### ISSUE TITLE
Can use it to built my own control?

### ISSUE THREAD

**Issue by kykm1307** [menees/Diff.Net#4]
Any compare code function that i can use in this code so that i can build my own control since it only view and cannot edit?

**Comment by menees** [comment]
The current Diff.Net project is just a WinForms application that uses the [Menees.Diffs and Menees.Diffs.Windows.Forms](https://github.com/menees/Libraries) libraries (which I also linked to in your issue #3). The Menees.Diffs library contains classes for doing UI-agnostic text diffs, so you can use it to get a diff and then write your own control to display the diff.

These open source projects _are_ the samples, so you'll have to research them thoroughly for how to use the libraries. The [Libraries issue #1](https://github.com/menees/Libraries/issues/1) may help you get started. The tests in [TextDiffTests.cs](https://github.com/menees/Libraries/blob/master/tests/Menees.Diffs.Tests/TextDiffTests.cs) may also help you.
